apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fb9a0hx6y-java-quarkus
  janus-idp.io/tekton: fb9a0hx6y-java-quarkus
  backstage.io/kubernetes-id: fb9a0hx6y-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fb9a0hx6y-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
